

###
POST  http://localhost:3000/pets
Content-Type: application/json

{
    "age":65,
    "kind":"cat",
    "name":"pablo"
}

###

PATCH  http://localhost:3000/pets
Content-Type: application/json

{
    "age":69,
    "kind":"cat",
    "name":"pablo"
}

###

DELETE   http://localhost:3000/pets/6
Content-Type: application/json