
###
GET   http://localhost:3000/pets
Content-Type: application/json

###
GET   http://localhost:3000/pets/7
Content-Type: application/json

###
POST  http://localhost:3000/pets
Content-Type: application/json

{
    "age":65,
    "kind":"cat",
    "name":"pablo"
}

###

PATCH  http://localhost:3000/pets
Content-Type: application/json

{
    "age":23,
    "kind":"rainbow",
    "name":"fido"
}

###

DELETE   http://localhost:3000/pets/7
Content-Type: application/json